## This is a simple test file

# !remind now This is a reminder
# !remind 1996-12-19T16:39:57-08:00 This is long overdue
# !remind 3000-01-01T00:00:00 We're long gone when this should fire

[server]
address = "localhost:8901"
owner = "phoenix"