## This is a simple test file

# !remind now This reminder will always fire.
# !remind 1996-12-19T16:39:57-08:00 This is long overdue ...
# !remind 3000-01-01T00:00:00 Hopefully never triggers.

[server]
address = "localhost:8901"
owner = "phoenix"

# !noremind - Stop further processing of reminders
# !remind - This reminder will never be processed.

[storage]
dir = /var/lib/r5d
