## This is an example configuration file in toml format.
## The contents of the file don't matter. The purpose is to show how
## reminders can be integrated in such a file via commented out lines.

## Those are some reminders. They are not visible to the toml configuration
## but are processed by r5d:
# !remind now This reminder will always fire.
# !remind 1996-12-19T16:39:57-08:00 This is long overdue ...
# !remind 3000-01-01T00:00:00 Hopefully never triggers.

[server]
address = "localhost:8901"
owner = "phoenix"

## The !noremind macro (this one) stops further processing of reminders
## The following reminder will never be processed:
# !remind - This reminder will never be processed.

[storage]
dir = /var/lib/r5d
