## Tiny example configuration for r5d

[server]
# !todo 2025-08-31 Switch to port 9001 (contact support)
address = "localhost:8901"
# !remind now Change the owner now!
owner = "phoenix"

## !noremind Tell r5d to ignore next reminders

[storage]
# !todo This will never trigger
dir = /var/lib/r5d
